# Generated by Django 3.2.5 on 2021-08-10 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('due_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='due_date')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.CharField(max_length=240, verbose_name='description')),
                ('file_address', models.CharField(max_length=240, verbose_name='file_address')),
                ('max_score', models.SmallIntegerField(verbose_name='max_score')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='-1', max_length=40, unique=True, verbose_name='username')),
                ('first_name', models.CharField(max_length=40, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=40, verbose_name='last_name')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('file_address', models.CharField(max_length=240, verbose_name='file_address')),
                ('assignment_id', models.ForeignKey(default='-1', on_delete=django.db.models.deletion.DO_NOTHING, to='dassessment.assignment')),
                ('username', models.ForeignKey(default='-1', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('score', models.SmallIntegerField(verbose_name='score')),
                ('assignment_id', models.ForeignKey(default='-1', on_delete=django.db.models.deletion.DO_NOTHING, to='dassessment.assignment')),
                ('username', models.ForeignKey(default='-1', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
