# Generated by Django 3.2.5 on 2021-08-20 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dassessment', '0002_alter_assessment_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='assignment_id',
        ),
        migrations.AddField(
            model_name='assessment',
            name='submission_id',
            field=models.ForeignKey(default='-1', on_delete=django.db.models.deletion.DO_NOTHING, to='dassessment.submission'),
        ),
    ]
