# Generated by Django 3.2.5 on 2021-08-20 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dassessment', '0005_auto_20210820_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='assignment_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='dassessment.assignment'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='username',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
